- name: create web app
  hosts: localhost
  tasks:
  - name: db container
    docker_container:
      name: db_test
      image: akshay30314/mysqlgslab
      state: started

  - name: app container
    docker_container:
      name: web_test
      image: akshay30314/guri
      ports:
      - "8080:80"
      state: started
      links:
      - db_test:db
