apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: ubuntu
    command: ["/bin/entrypoint.sh"]
    volumeMounts:
    - name: wrapper
      mountPath: /bin/entrypoint.sh
#      readOnly: true
      subPath: entrypoint.sh
  volumes:
  - name: wrapper
    configMap:
      defaultMode: 0777
      name: wrapper
